name: Proxy Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests toml pysocks

    - name: Run proxy checker
      run: python your_script_name.py

    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lastData.txt
        git commit -m "Update proxy list" || echo "No changes to commit"
        git push origin master  # 假设你的主分支是 master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'schedule' && ! (git diff --quiet HEAD -- lastData.txt) # 仅在文件更改时
