name: Proxy Checker

on:
  # 手动触发
  workflow_dispatch:
  # 定时触发 (每天一次, 时间根据需要调整)
  schedule:
      - cron: '0 0 * * *'  # 每天 00:00 UTC 时间执行

jobs:
  check_proxies:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v3  # 设置 Python 环境
      with:
        python-version: '3.10'  # 指定 Python 版本, 根据需要选择

    - name: Install dependencies
      run: pip install requests toml pysocks  # 安装依赖

    - name: Run proxy checker
      run: python your_script_name.py  # 运行你的脚本 (替换为你的脚本文件名)

    - name: Commit results (Optional)
      # 如果你想把 lastData.txt 的变化提交回仓库, 可以添加这个步骤
      # 注意: 这需要配置 git 的用户名和邮箱, 并且可能需要使用 personal access token
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lastData.txt
        git commit -m "Update proxy list" || echo "No changes to commit"
        git push
      if: github.event_name == 'schedule'  # 仅在定时任务触发时提交 (可选)
