name: Proxy Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests toml pysocks

    - name: Run proxy checker
      run: python your_script_name.py

    - name: Check for changes and commit
      uses: actions/github-script@v6  # 使用 github-script
      if: github.event_name == 'schedule' # 仅计划任务
      with:
        script: |
          const { execSync } = require('child_process');
          try {
            // 检查 lastData.txt 是否有变化
            execSync('git diff --exit-code --quiet HEAD -- lastData.txt');
            console.log('No changes to lastData.txt. Skipping commit.');
            return; // 没有变化，退出
          } catch (error) {
             // 有变化, 继续执行提交
            console.log('Changes detected in lastData.txt. Committing...');
          }

          // 配置 Git 并提交
          execSync('git config --local user.email "action@github.com"');
          execSync('git config --local user.name "GitHub Action"');
          execSync('git add lastData.txt');
          execSync('git commit -m "Update proxy list"');
          execSync('git push origin master'); # 假设你的主分支是master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
